version: 2.1
orbs:
  python: circleci/python@2.1.1

workflows:
  sample:
    jobs:
      - build-and-test

jobs:
  build-and-test:
    description: "Setup Flask and run tests"
    executor: python/default
    # docker:
    #   - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest -v